config/routes.rb
      get :finalize_after_otp
      get :finalize_after_redirect
      post :generate_stored_card_nonce
      get :adyen_payment_methods
      get :adyen_finalize_after_redirect
      get :dropin
      get :splits_collaborator_popup
    end
  end

  resources :history,       only: [:index, :show]

  resources :subscriptions do
    collection do
      post :keep
      post :cancel
      post :change_card

      get :select_card
      get  :buy
      post :buy
    end
  end

  resources :tour_dates
  resources :band_photos

  resources :sales_reports

  resources :purchases do
    delete :remove_code, on: :member

    collection do
      delete :remove_all_for_store
      delete :remove_all_salepoint_subscriptions
      delete :remove_all_for_expander
    end
  end

  resources :itunes_links

  scope("/cart/purchases/:purchase_id", as: "purchase") do
    resource :cert, controller: "cert"
  end

  #
  # Invoices
  #
  resources :invoices, only: [:show] do
    get :thanks, on: :member
    get :download, on: :member, format: true, defaults: { format: 'pdf' }
    get :refunds, on: :member

    resources :credit_note_invoices, only: [:show]
  end

  #
  # Albums
  #
  resources :albums, controller: 'album' do
    member do
      get :edit_linernotes
      get :preview_artist, to: "preview_artists#show"
      get :preview_title, to: "preview_titles#show"
      get :confirm_delete
      get :distribution_panel
      get :distribution_songs_status
      get :album_meta_data
      get :get_myspace_page
      get :monetize, to: redirect("/youtube_tracks/dashboard")
      get :confirm_monetize
      post :confirm_monetize
      get :update_renewal
      get :edit_renewal
      get :stop_cancellation
      get :cyrillic_release
      get :get_preorder_data
    end

    resource :track_order, controller: 'track_order'
    resources :songs do
      member do
        get :new_upload
        get :delete
        get :preview_title, to: "preview_titles#show"
      end
    end

    resource  :artwork, controller: "artwork"
    resources :artwork_suggestions do
      member do
        get :preview
      end
    end

    resources :purchases, controller: 'album_purchases'

    resources :salepoints do
      resource :artwork_template, controller: 'artwork_template'
      collection do
        get :discovery_platforms
        post :activate_itunes_ww
      end
    end

    resource :salepoint_subscriptions, only: [:create, :destroy]
    resources :salepoint_subscriptions, only: [] do
      get :toggle_active, on: :member
    end
  end

  delete "royalty_split_songs/:royalty_split_song_id", to: "royalty_splits#remove_song", as: :destroy_royalty_split_song
  resources :royalty_splits, except: [:create] do
    collection do
      post "/new", to: "royalty_splits#create", as: :create
      get :albums
      post "/add_songs", to: "royalty_splits#add_songs", as: :add_songs_to
      get "/invited", to: "royalty_splits#invited_splits", as: :invited
      get :invited_splits_onboarding
      post "/accept_all_splits", to: "royalty_splits#accept_all_splits", as: :accept_all
    end
    post "/accept_split", to: "royalty_splits#accept_split", as: :accept, on: :member
  end

  resources :my_artists, only: [:index, :show] do
    post :mapping, to: "artist_mappings#create"
  end

  resources :videos, only: [:index, :show]

  resources :notifications, only: [:index] do
    get :dropdown, on: :collection
    get :archive,   on: :member
    post :action,   on: :member
  end

  resources :product_reports, only: [:index] do
    get :detail_reports, on: :collection
    get :preorder_reports, on: :collection
  end

  namespace :ytm do
    resources :salepoint_songs, only: [:index] do
      post :update, on: :collection
      get :play_song
    end

    resources :salepoints, only: [:update]
  end
  resources :stored_credit_cards, except: [:show] do
    collection do
      get :country_cities
    end
  end
  resources :stored_paypal_accounts, only: [:destroy] do
    collection do
      get :ec_step1
      get :ec_step3
      get :error
    end
  end
  #
  # Publishing stuff
  #
  resources :compositions, controller: 'song_registrations' do
    collection do
      get :paginate
      get :resolve_disputes
      post :send_disputes
    end
  end

  resources :publishing_composition_splits do
    collection do
      get :paginate
      post :confirm_splits
    end
  end

  resources :composers do
    member do
      patch :update_cae_number
    end
    resource :tax_info
  end

  namespace :publishing_administration do
    resources :congratulations, only: [:show]
    resources :enrollments, only: [:show, :new, :create, :edit, :update]
    resources :terms_and_conditions, only: [:show, :update]
    resources :compositions, only: [:show]
    resources :composers, only: [:index, :edit, :update] do
      member do
        post :resend_lod
        post :sync_opt_in
        post :sync_opt_out
      end
    end

    resources :publishing_composers, only: [:index, :edit, :update] do
      member do
        post :resend_lod
        post :sync_opt_in
        post :sync_opt_out
      end

      resources :publishing_compositions, only: [:index]
      resources :publishing_terms_and_conditions, only: [:show, :update]
    end
  end

  resources :legal_documents, only: :show

  resources :mastered_tracks, to: redirect("http://aftermaster.tunecore.com")

  resources :friend_referral do
    collection do
      get :signup
      get :referee_list
      get :payouts
    end
  end

  get "refer-a-friend", to: 'friend_referral#new'

  resources :song_library_uploads, only: [:create]

  resources :new_reports, only: [:index] do
    get :refresh, on: :collection
  end

  resources :payout_provider_registrations, only: [:create]
  resources :payout_provider_logins, only: :create
  resource  :payout_provider_registration_landings, only: :show
  resource  :payout_provider_login_landings, only: :show

  resources :payout_transfers, only: [:new, :create, :show] do
    post :confirm, on: :collection
  end

  resource :balance_histories, only: [:show], path: "balance_history" do
    collection do
      get :filter, to: "balance_histories/filters#show"
    end
  end

  namespace :webhooks do
    post 'sift', to: 'sift/webhooks#update', if: FeatureFlipper.show_feature?(:sift_webhooks)
  end

  #######################################################################################
  #######################################################################################
  ################ PLACE ALL ADMIN ROUTES IN THE FOLLOWING NAMESPACE ####################
  #######################################################################################
  #######################################################################################

  namespace :admin do
    resources :songs do
      get :play_song
    end

    resources :foreign_exchange_pegged_rates, only: [:index, :create, :new] do
      get :preview_price, on: :collection
    end
    resources :track_monetization_judgements, only: [] do
      collection do
        post :mass_judgement
      end
    end
    resources :youtube_track_monetization_judgements, only: [:index]
    resources :facebook_track_monetization_judgements, only: [:index]
    resource :mass_monetization_block, only: [:show, :create]
    resources :legal_documents, only: :show

    resource :mass_retry_songs, only: [:show, :create] do
      post :encumbrance_info
    end

    namespace :payment do
      post :mass_pay_paypal
      post :mass_pay_check
      post :cancel_payment
      post :process_payment
    end
    resources :delivery_batches, only: [:index] do
      post :send_batch_complete, to: "batch_completes#create"
    end

    resource :add_salepoint, only: [:edit, :update]

    resources :composers_managers, only: [:show, :edit, :update, :destroy] do
      post :imports, to: "composers_managers_imports#create"
    end

    resources :publishing_composers_managers, only: [:show, :edit, :update, :destroy] do
      post :imports, to: "publishing_composers_managers_imports#create"
    end

    resources :composers, only: :show do
      resources :compositions, only: [:index, :update] do
        collection do
          get :search
          get :download_csv
        end
        member do
          put :update_status
          put :update_eligibility
        end
      end
      collection do
        get  :list
        get  :download_client_import
      end
    end

    namespace :accounts, path: "/accounts/:account_id" do
      resources :composers, only: [:edit, :update] do
        get :terms_of_service
      end

      resources :publishing_composers, only: [:edit, :update] do
        get :terms_of_service
      end
    end

    namespace :accounts, path: "/accounts/:account_id" do
      resources :publishing_composers, only: [:edit, :update] do
        get :terms_of_service
        post :update_lod
      end
    end

    resources :terminated_composers, only: [:new, :create, :show, :update, :destroy]
    resources :publishing_terminated_composers, only: [:new, :create, :show, :update, :destroy]
    resources :composer_sync_opt_ins, only: [:destroy]
    resources :publishing_composer_sync_opt_ins, only: [:destroy]
    resources :delivery_batches, only: [:index] do
      post :send_batch_complete, to: "batch_completes#create"
    end
    resources :tax_tokens_cohorts do
      resources :tax_tokens, only: [:index, :update]
      post :remove_cohort, to: "tax_tokens_cohorts#remove_cohort", on: :collection
    end

    put "/update_tax_tokens", to: "tax_tokens#update"

    resources :delete_accounts, only: [:new, :create]
    resources :bulk_album_approvals, only: [:index, :new, :create]
    resources :mass_adjustments, only: [:index, :new, :create, :show, :update]

    root to: "dashboard#index", as: :home
    resources :dashboard, only: [:index] do
      collection do
        get :processing_albums
        post :search
      end
    end

app/controllers/admin/notifications_controller.rb
class Admin::NotificationsController < Admin::AdminController
  before_action :require_notification_role

  def index
    @term = params[:term]
    @notifications = \
      TargetedNotification
      .order("created_at DESC")
      .paginate(page: (params[:page] || 1).to_i)

    return unless @term

    @notifications = @notifications.where("lower(targeted_notifications.title) like ? or lower(targeted_notifications.text) like ?", "%#{@term.downcase}%", "%#{@term.downcase}%")
  end

  def show
    @notification = TargetedNotification.find(params[:id])
    @people_in_notifications = \
      Notification
      .where(targeted_notification_id: @notification.id)
      .paginate(page: params[:page])
  end

  def edit
    @notification = TargetedNotification.find(params[:id])
  end

  def update
    @notification = TargetedNotification.find(params[:id])

    if targeted_notification_params[:notification_icon_id]
      @notification.notification_icon_id = targeted_notification_params[:notification_icon_id]
    end

    @notification.notification_icon = NotificationIcon.new(file: params[:file]) if params[:file]

    if @notification.update(targeted_notification_params)
      flash[:success] = "You have successfully updated the notification"
      redirect_to admin_notification_path(@notification)
    else
      render :edit
    end
  end

  def new
    @notification = TargetedNotification.new
  end

  def create
    @notification = TargetedNotification.new(targeted_notification_params)
    @notification.person = current_user

    if targeted_notification_params[:notification_icon_id]
      @notification.notification_icon_id = targeted_notification_params[:notification_icon_id]
    end

    @notification.notification_icon = NotificationIcon.new(file: params[:file]) if params[:file]

    if @notification.save
      flash[:success] = "Successfully created a notification"
      redirect_to admin_notification_path(@notification)
    else
      render :new
    end
  end

  def destroy
    @notification = TargetedNotification.find(params[:id])

    if @notification.destroy
      flash[:success] = "Successfully deleted the notification"
      redirect_to admin_notifications_path
    else
      flash[:error] = "Could not delete the notification"
      render :show
    end
  end

  def add_people
    @notification = TargetedNotification.find(params[:id])

    @new_notifications = @notification.add_people_from_csv(params[:add_people_csv])

    if @new_notifications != false
      flash[:success] = "Successfully added #{@new_notifications.size} from CSV"
      redirect_to admin_notification_path(@notification)
    else
      flash[:error] = "Cannot add people to global notifications"
      redirect_to admin_notification_path(@notification)
    end
  end

  private

  def targeted_notification_params
    params
      .require(:targeted_notification)
      .permit(
        :text,
        :url,
        :global,
        :title,
        :link_text,
        :notification_icon_id
      )
  end

  def require_notification_role
    return if current_user.has_role?("Notifications")

    flash[:error] = "You do not have access to this function"
    redirect_to admin_home_path
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  layout "application"

  before_action :load_person

  def index
    params[:page]     ||= 1
    params[:per_page] ||= 10
    if @person.notifications.present?
      @start_date = @person.notifications.last.effective_created_at
      @end_date = @person.notifications.first.effective_created_at
      @notification_dates = Utilities::FormDateRange.create_range(@start_date, @end_date)
    end

    @notifications = @person.notifications
                            .read(params[:status_select])
                            .range(params[:date_from_select], params[:date_to_select])
                            .paginate(page: params[:page], per_page: params[:per_page])

    respond_to do |format|
      format.html
      format.js do
        render partial: "notifications_archive", locals: { notifications: @notifications }, content_type: "text/html"
      end
    end
  end

  # Dropdown
  # this is where the notifications come from
  def dropdown
    @notifications = Notification.unarchived_notifications(@person)
    Notification.mark_seen(@person, @notifications)

    respond_to do |format|
      format.html { render layout: false }
      format.js { head :ok }
    end
  end

  #
  # Marks a notification as actioned
  #
  def action
    @notification = @person.notifications.find(params[:id])

    Notification.transaction do
      @notification.mark_actioned
      Notification.mark_seen(@person, [@notification])
    end

    respond_to do |format|
      format.html { head :ok }
      format.js { head :ok }
    end
  end

  #
  # Marks a notification as archived
  #
  def archive
    @notification = @person.notifications.find(params[:id])
    @notification.mark_archived

    respond_to do |format|
      format.html { head :ok }
      format.js { head :ok }
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def notification_class(notification)
    if notification.first_clicked.blank?
      "unread"
    else
      "read"
    end
  end
end

app/views/notifications/_notifications_archive.html.erb
<div id="notifications_archive">
  <% unless notifications.empty? %>
  <div class="pager">
    <div class="pager-total"><%= "#{notifications.total_entries} #{custom_t(".notifications", count: notifications.total_entries)}" %></div>
    <div class="pager-controls">
      <% if notifications.current_page > 1 %>
        <%= link_to '<i class="fa fa-caret-left fa-lg fa-2x"></i>'.html_safe, notifications_path(:page => notifications.current_page - 1), :remote=>true, :class => "page_link pager-left" %>
      <% else %>
        <span class="pager-left"><i class="fa fa-caret-left fa-lg fa-2x"></i></span>
      <% end %>

      <%= form_tag(notifications_path, :remote => true, :class => "page_select_form pager-select", :method => :get) do %>
        <span><%= custom_t(".page") %></span>
        <%= select_tag("page", options_for_select((1..notifications.total_pages).collect{ |page| [page,page] }, notifications.current_page)) %>
        <span><%= custom_t(".of") %> <strong><%= notifications.total_pages %></strong></span>
      <% end %>

      <% if notifications.current_page < notifications.total_pages %>
        <%= link_to '<i class="fa fa-caret-right fa-lg fa-2x"></i>'.html_safe, notifications_path(:page => notifications.current_page + 1), :remote => true, :class => "page_link pager-right" %>
      <% else %>
        <span class="pager-right"><i class="fa fa-caret-right fa-lg fa-2x"></i></span>
      <% end %>
    </div>
  </div>
  <% end %>

  <ul class="notification_items">
    <% if notifications.each do |notification| %>
      <li class="notifications_item <%= notification_class(notification) %>">
        <a href="<%= notification.url %>" class="notification_action" data-action-url="<%= action_notification_path(notification) %>" data-notification-id="<%= notification.id %>">
          <% unless notification.image_url.blank? %><p class="image"><%= image_tag notification.image_url %></p><% end %>
          <span class="title">
            <%= notification.title %>
            <span class="time"><%= time_ago_in_words(notification.effective_created_at) %></span>
          </span>
          <span class="description">
            <%= notification.text.html_safe %> <span class="faux_link"><%= notification.link_text %></span>
          </span>
        </a>
      </li>
    <% end.empty? %>
      <li class="notifications_item empty_item">
        <p class="description"><%= custom_t(".no_notifs") %></p>
      </li>
    <% end %>
  </ul>

  <% unless notifications.empty? %>
  <div class="pager">
    <div class="pager-controls">
      <% if notifications.current_page > 1 %>
        <%= link_to '<i class="fa fa-caret-left fa-lg fa-2x"></i>'.html_safe, notifications_path(:page => notifications.current_page - 1), :remote=>true, :class => "page_link pager-left" %>
      <% else %>
        <span class="pager-left"><i class="fa fa-caret-left fa-lg fa-2x"></i></span>
      <% end %>

      <%= form_tag(notifications_path, :remote => true, :class => "page_select_form pager-select", :method => :get) do %>
        <span><%= custom_t(".page") %></span>
        <%= select_tag("page", options_for_select((1..notifications.total_pages).collect{ |page| [page,page] }, notifications.current_page)) %>
        <span><%= custom_t(".of") %> <strong><%= notifications.total_pages %></strong></span>
      <% end %>

      <% if notifications.current_page < notifications.total_pages %>
        <%= link_to '<i class="fa fa-caret-right fa-lg fa-2x"></i>'.html_safe, notifications_path(:page => notifications.current_page + 1), :remote => true, :class => "page_link pager-right" %>
      <% else %>
        <span class="pager-right"><i class="fa fa-caret-right fa-lg fa-2x"></i></span>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/notifications/dropdown.html.erb
<% if @notifications.empty? %>
  <li class="notifications_item"><span class="no_notification"><%= custom_t(".no_new_notifs") %></span></li>
<% else %>
  <% @notifications.each do |notification| %>
    <li class="notifications_item <%= notification_class(notification) %>">
      <%= link_to "<i class='fa fa-times'></i>".html_safe, archive_notification_path(notification), :class => "hide_notification", :remote => true %>
      <a href="<%= notification.url %>" class="notification_action" data-action-url="<%= action_notification_path(notification) %>" data-notification-id="<%= notification.id %>">
        <% unless notification.image_url.blank? %><p class="image"><%= image_tag notification.image_url %></p><% end %>
        <div class="text">
          <span class="title">
            <%= notification.title %>
            <span class="time"><%= time_ago_in_words(notification.effective_created_at) %> <%= custom_t(".notifications.ago") %></span>
          </span>
          <span class="description"><%= notification.text.html_safe %> <span class="faux_link"><%= notification.link_text %></span></span>
        </div>
      </a>
    </li>
  <% end %>
<% end %>

app/views/notifications/index.html.erb
<% content_for :css do %>
  <%= stylesheet_link_tag "/stylesheets/internal_layout.css" %>
  <%= stylesheet_link_tag "/stylesheets/notifications.css" %>
<% end %>

<div class="content">
  <header>
    <div class="row">
      <div class="twelve columns">
        <section class="page_title">
          <h1><%= custom_t(".notifications") %></h1>
        </section>
      </div>
    </div>
  </header>

  <div class="row">
    <section class="notifications_page eight columns">
      <%= render :partial => "notifications_archive", :locals => { :notifications => @notifications } %>
    </section>

    <div class="sidebar four columns">
      <section class="filter">
        <header>
          <h3><%= custom_t(".filter") %></h3>
        </header>
        <%= form_tag notifications_path, :method => 'get', :class => 'filter_form' do %>
          <div class="status">
            <label for="status_select"><%= custom_t(".status") %></label>
            <select name="status_select" id="status_select">
              <option value=""><%= custom_t(".any_status") %></option>
              <option value="1" <%= params[:status_select].include?('1') ? 'selected' : '' if params[:status_select] %>>read</option>
              <option value="0" <%= params[:status_select].include?('0') ? 'selected' : '' if params[:status_select] %>>unread</option>
            </select>
          </div>
          <% unless @notification_dates.blank? %>
          <div class="date">
            <label for="date_from_select"><%= custom_t(".date_from") %></label>
            <%= select_tag "date_from_select", options_for_select(@notification_dates, :selected => params[:date_from_select] || Date.parse(@notification_dates.first[1])) %>
            <label for="date_to_select"><%= custom_t(".date_to") %></label>
            <%= select_tag "date_to_select", options_for_select(@notification_dates, :selected => params[:date_to_select] || Date.parse(@notification_dates.last[1])) %>
          </div>
          <% end %>
          <fieldset class="filter-buttons">
            <input type="submit" name="submit" class="button-callout-alt" value="<%= custom_t('.apply') %>">
            <input type="reset" name="reset" class="button-interface" value="<%= custom_t('.clear') %>">
          </fieldset>
        <% end %>
      </section>
    </div>
  </div>
</div>